name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  MAVEN_ARGS: "--no-transfer-progress --errors --fail-at-end --show-version"

jobs:
  build:
    name: build and analyze
    strategy:
      matrix:
        java: [ '17', '21' ]
        os: [ 'ubuntu-latest', 'macos-latest', 'windows-latest' ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: maven
      - name: Build
        run: ./mvnw $MAVEN_ARGS -Pcoverage clean verify
      - name: Analyse with SonarCloud
        if: ${{ matrix.java == 21 && matrix.os == 'ubuntu-latest' }}
        run: >
          ./mvnw $MAVEN_ARGS -Pcoverage verify
          sonar:sonar
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
          -Dsonar.organization=fkaratas
          -Dsonar.projectKey=fkaratas_whitelabel-password-generator
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}        
